import type { GameObject } from "../adapter/types.ts";

/**
 * Pick the Scryfall lookup name and faceIndex for a battlefield game object.
 *
 * `scryfall-data.json` is generated by `scripts/gen-scryfall-images.sh`, which
 * indexes only front-face names (plus the card's canonical name when it
 * differs). Back-face names of DFCs/transforming Sagas are never keys in that
 * map — this is an explicit choice in the generator to avoid cross-card
 * collisions (see the comment in that script).
 *
 * However, the engine's `transform_permanent` swaps `obj.name` to the
 * back-face name when a permanent transforms, and moves the original
 * front-face characteristics into `obj.back_face`. As a result, after
 * transform a naive Scryfall lookup by `obj.name` fails with "card image not
 * in local data" — no image renders (see issue #90 for The Legend of Kuruk).
 *
 * This helper resolves the correct pair so renderers always fetch the image
 * off the indexed front-face entry:
 *   - Not transformed → `{ name: obj.name, faceIndex: 0 }` (front of a plain
 *     card or an untransformed DFC/Saga).
 *   - Transformed → `{ name: obj.back_face.name, faceIndex: 1 }` — the stored
 *     front-face name is guaranteed to be a valid Scryfall key, and
 *     `faceIndex: 1` selects the back image within that indexed entry.
 *
 * If transformed but `back_face` is somehow absent, we fall back to the
 * current `obj.name` + `faceIndex: 1`; the lookup will still miss, but we
 * avoid crashing and preserve prior behavior.
 */
export function cardImageLookup(
  obj: Pick<GameObject, "name" | "transformed" | "back_face">,
): { name: string; faceIndex: number } {
  if (obj.transformed) {
    return {
      name: obj.back_face?.name ?? obj.name,
      faceIndex: 1,
    };
  }
  return { name: obj.name, faceIndex: 0 };
}
